//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strafrunden.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strafrunden.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die automatisch ähnelt.
        /// </summary>
        public static string automatic {
            get {
                return ResourceManager.GetString("automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisch aktualisieren ähnelt.
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten löschen ähnelt.
        /// </summary>
        public static string ClearData {
            get {
                return ResourceManager.GetString("ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zusammengefasst ähnelt.
        /// </summary>
        public static string combined {
            get {
                return ResourceManager.GetString("combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zusammengefasste Fehlwürfe ähnelt.
        /// </summary>
        public static string CombinedFails {
            get {
                return ResourceManager.GetString("CombinedFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlwürfe kombinieren ähnelt.
        /// </summary>
        public static string CombineFails {
            get {
                return ResourceManager.GetString("CombineFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erzeuge Hauptfenster... ähnelt.
        /// </summary>
        public static string CreatingMainWindow {
            get {
                return ResourceManager.GetString("CreatingMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankdatei erstellt! ähnelt.
        /// </summary>
        public static string DatabaseCreated {
            get {
                return ResourceManager.GetString("DatabaseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die detailiert ähnelt.
        /// </summary>
        public static string detailed {
            get {
                return ResourceManager.GetString("detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für die korrekte Funktion des Servers müssen Ports freigegeben werden. Dies benötigt Administratoren-Rechte. ähnelt.
        /// </summary>
        public static string ErrorPortsNotFree {
            get {
                return ResourceManager.GetString("ErrorPortsNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für die korrekte Funktion des Servers müssen URLs freigegeben werden. Dies benötigt Administratoren-Rechte. ähnelt.
        /// </summary>
        public static string ErrorURLNotFree {
            get {
                return ResourceManager.GetString("ErrorURLNotFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Export: ähnelt.
        /// </summary>
        public static string ExcelExport {
            get {
                return ResourceManager.GetString("ExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Datei: ähnelt.
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jetzt exportieren! ähnelt.
        /// </summary>
        public static string ExportNow {
            get {
                return ResourceManager.GetString("ExportNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regelmäßig exportieren ähnelt.
        /// </summary>
        public static string ExportRegular {
            get {
                return ResourceManager.GetString("ExportRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlwürfe ähnelt.
        /// </summary>
        public static string Fails {
            get {
                return ResourceManager.GetString("Fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabefehler.
        ///{0}  ist möglicherweise geöffnet! ähnelt.
        /// </summary>
        public static string FIleOpenErrorFromat {
            get {
                return ResourceManager.GetString("FIleOpenErrorFromat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rufe SQL-Server Instanzen ab... ähnelt.
        /// </summary>
        public static string GettingSQLInstances {
            get {
                return ResourceManager.GetString("GettingSQLInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version:{0}
        ///(c) Friedrich May
        ///
        ///Der Server ist erreichbar unter den folgenden IP-Adressen:{1} ähnelt.
        /// </summary>
        public static string HelpFormat {
            get {
                return ResourceManager.GetString("HelpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Aktualisierung: ähnelt.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Datenbank... ähnelt.
        /// </summary>
        public static string LoadingDatabase {
            get {
                return ResourceManager.GetString("LoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Strafrundenserver... Bitte warten! ähnelt.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Einstellungen... ähnelt.
        /// </summary>
        public static string LoadingSettings {
            get {
                return ResourceManager.GetString("LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade... ähnelt.
        /// </summary>
        public static string LoadingTitle {
            get {
                return ResourceManager.GetString("LoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die manuell ähnelt.
        /// </summary>
        public static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geben sie bitte nur Zahlen ein! ähnelt.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL-Verbindung geöffnet! ähnelt.
        /// </summary>
        public static string OpenedSQL {
            get {
                return ResourceManager.GetString("OpenedSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne Firewall... ähnelt.
        /// </summary>
        public static string OpenFirewall {
            get {
                return ResourceManager.GetString("OpenFirewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffne SQL-Verbindung... ähnelt.
        /// </summary>
        public static string OpeningSQL {
            get {
                return ResourceManager.GetString("OpeningSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind sie sicher, dass sie alle Daten löschen möchten? ähnelt.
        /// </summary>
        public static string QuestionDeleteData {
            get {
                return ResourceManager.GetString("QuestionDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchsuchen... ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel-Datei wählen oder erstellen... ähnelt.
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen upgegraded! ähnelt.
        /// </summary>
        public static string SettingsUpgraded {
            get {
                return ResourceManager.GetString("SettingsUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungsversion ähnelt.
        /// </summary>
        public static string SettingsVersion {
            get {
                return ResourceManager.GetString("SettingsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Richte neue Datembank ein... ähnelt.
        /// </summary>
        public static string SettingUpDatabase {
            get {
                return ResourceManager.GetString("SettingUpDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gebe URL frei... ähnelt.
        /// </summary>
        public static string SetURLACL {
            get {
                return ResourceManager.GetString("SetURLACL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individuelle Wurfrunden anzeigen ähnelt.
        /// </summary>
        public static string ShowIndividual {
            get {
                return ResourceManager.GetString("ShowIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL-Server ähnelt.
        /// </summary>
        public static string SQLServer {
            get {
                return ResourceManager.GetString("SQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startnummer ähnelt.
        /// </summary>
        public static string Starter {
            get {
                return ResourceManager.GetString("Starter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;&lt;head&gt;&lt;title&gt;Strafrundeneingabe&lt;/title&gt;&lt;link rel=&apos;stylesheet&apos; href=&apos;main.css&apos;&gt;&lt;/script&gt;&lt;meta name=&apos;viewport&apos; content=&apos;width = device-width, initial-scale = 1&apos;/&gt;&lt;/head&gt;&lt;body&gt;&lt;div class = &apos;strafrundenForm&apos;&gt;&lt;h2&gt;Strafrunden Speichern:&lt;/h2&gt;&lt;form action=&apos;/strafrunden/&apos; method=&apos;post&apos;&gt;&lt;label for=&apos;nr&apos;&gt;Startnummer:&lt;/label&gt;&lt;input type=&apos;number&apos; name=&apos;nr&apos; autocomplete=&apos;off&apos;&gt;&lt;br/&gt;&lt;label for=&apos;trown&apos;&gt;Fehlwürfe:&lt;/label&gt;&lt;input type=&apos;number&apos; name=&apos;thrown&apos; autocomplete=&apos;off&apos; min=&apos;0&apos; max=&apos;3&apos;&gt;&lt;br/&gt;&lt;input type=&apos;submit&apos; valu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string StrafrundenHTMLTemplate {
            get {
                return ResourceManager.GetString("StrafrundenHTMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wurfrunden-ID ähnelt.
        /// </summary>
        public static string ThrowID {
            get {
                return ResourceManager.GetString("ThrowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strafrunden ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnung ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
