//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strafrunden.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal templates() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strafrunden.Properties.templates", typeof(templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;&lt;head&gt;&lt;title&gt;{6}&lt;/title&gt;&lt;link rel=&apos;stylesheet&apos; href=&apos;main.css&apos;&gt;&lt;/script&gt;&lt;meta name=&apos;viewport&apos; content=&apos;width = device-width, initial-scale = 1&apos;/&gt;&lt;/head&gt;&lt;body&gt;&lt;div class = &apos;strafrundenForm&apos;&gt;&lt;h2&gt;{5}:&lt;/h2&gt;&lt;form action=&apos;/strafrunden/&apos; method=&apos;post&apos;&gt;&lt;label for=&apos;nr&apos;&gt;{4}:&lt;/label&gt;&lt;input type=&apos;number&apos; name=&apos;nr&apos; autocomplete=&apos;off&apos;&gt;&lt;br/&gt;&lt;label for=&apos;trown&apos;&gt;{6}:&lt;/label&gt;&lt;input type=&apos;number&apos; name=&apos;thrown&apos; autocomplete=&apos;off&apos; min=&apos;0&apos; max=&apos;3&apos;&gt;&lt;br/&gt;&lt;input type=&apos;submit&apos; value=&apos;{7}&apos;&gt;&lt;/form&gt;&lt;/div&gt;&lt;div class=&apos;lastSavedDispl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Strafrunden {
            get {
                return ResourceManager.GetString("Strafrunden", resourceCulture);
            }
        }
    }
}
